---
booktitle: Proceedings of Thirty Sixth Conference on Learning Theory
shortname: COLT
volume: '195'
year: '2023'
published: 2023-07-12
start: 2023-07-12
end: 2023-07-15
conference_number: '36'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: COLT2023
month: 0
cycles: false
bibtex_editor: Neu, Gergely and Rosasco, Lorenzo
editor:
- given: Gergely
  family: Neu
- given: Lorenzo
  family: Rosasco
title: Proceedings of Machine Learning Research
description: |
  Proceedings of Thirty Sixth Conference on Learning Theory
    Held in Bangalore, India on 12-15 July 2023

  Published as Volume 195 by the Proceedings of Machine Learning Research on 12 July 2023.

  Volume Edited by:
    Gergely Neu
    Lorenzo Rosasco

  Series Editors:
    Neil D. Lawrence
date_str: 12--15 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v195"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v195
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v195
email: ''
conference:
  name: The Thirty Sixth Annual Conference on Learning Theory
  url: https://learningtheory.org/colt2023/
  location: Bangalore, India
  dates:
  - 2023-07-12
  - 2023-07-13
  - 2023-07-14
  - 2023-07-15
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v195/colt23.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v195/colt23.bib
